// app messages
export const MESSAGES = {
    SIGNUP_SUCCESSFUL: "You have succesfully signed up!",
    SIGNUP_SUCCESS_MAIL: "Welcome to GoldenCoin. We hope you like it here!",
    SIGNUP_FAILED: "Sign up failed!",
    USER_NOT_FOUND: "User not found!",
    USER_ALREADY_EXISTS: "User already exists!",
    EMAIL_NOT_AVAILABLE: "Email is not available, please try again with a different email!",
    INVALID_CREDENTIALS: "Invalid username or password!",
    INVALID_OTP: "Invalid OTP!",
    INVALID_TOKEN: "Invalid token!",
    EXPIRED_TOKEN: "Token has expired, please request another verification!",
    NOT_LOGGED_IN: "You must be logged in to continue!",
    LOGIN_SUCCESSFUL: "You have successfully logged in!",
    LOGIN_SUCCESS_MAIL: "You successfully logged into your account. Please reach out to us immediately to reset your password if this wasn't you!",
    LOGIN_FAILED: "Login failed!",
    LOGOUT_SUCCESSFUL: "You have successfully logged out!",
    LOGOUT_FAILED: "Logout failed!",
    ALREADY_LOGGED_OUT: "You are already logged out!",
    PASSWORD_RESET_SUCCESSFUL: "Password reset successful!",
    PASSWORD_RESET_SUCCESS_MAIL: "Your password was reset successfully! Please send us a mail if this wasn't you!",
    PASSWORD_RESET_FAILED: "Password reset failed!",
    PASSWORD_RESET_URL_SENT: "Password reset link sent!",
    PASSWORD_CHANGE_SUCCESSFUL: "Password change successful!",
    PASSWORD_CHANGE_SUCCESS_MAIL: "Your password has been changed successfully. Please send us a mail if this wasn't you!",
    PASSWORD_CHANGE_FAILED: "Password change failed",
    EMAIL_VERIFICATION_REQUEST_SUCCESSFUL: "Email verification request sent successfully",
    EMAIL_VERIFICATION_SUCCESSFUL: "Email verified successfully",
    EMAIL_VERIFICATION_SUCCESS_MAIL: "Your email has been verified. Happy Trading!",
    EMAIL_VERIFICATION_FAILED: "Email verification failed!",
    USER_DELETE_SUCCESSFUL: "User deleted successfully!",
    USER_UPDATE_SUCCESSFUL: "User updated successfully!",
    PAGE_NOT_FOUND: "The resource you're looking for does not exist!",
}